### PR TITLE
Optimize generated encoders

### PR DESCRIPTION
**Pull request by CAFxX**
Fixes https://github.com/mailru/easyjson/issues/136

This changes the generated code for a `omitempty` field from:
```
	if in.Name != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
```

to:

```
	if in.Name != nil {
		if first {
			first = false
			out.RawString("\"name\":")
                } else {
			out.RawString(",\"name\":")
		}
		out.String(string(*in.Name))
	}
```

### CODE REVIEW

**Comment by CAFxX** [comment]
*gentle ping*

**Comment by rvasily** [comment]
There is some conflicts due to recent changes. Can you fix them, please?

**Comment by CAFxX** [comment]
@rvasily fixed the conflicts; do you have any feedback on the change itself?

**Comment by CAFxX** [comment]
@rvasily *ping*

in the meanwhile other conflicts cropped up: can you please take a look at it, and let me know if this is something that you may want to pull?

**Comment by rvasily** [comment]
i will merge pull it
i think this will resolve conflict
```
		fmt.Fprintln(g.out, ws+"    if "+tmpVar+"First { "+tmpVar+"First = false } else { out.RawByte(',') }")
		fmt.Fprintln(g.out, ws+"    "+fmt.Sprintf(keyEnc, tmpVar+"Name"))
```
please, check it, i will fix and merge then

**Comment by rvasily** [comment]
try to make it ast, before something changes again

**Comment by CAFxX** [comment]
@rvasily should be fixed now

**Comment by rvasily** [comment]
Merged
Thanks

**Pull request merged**
