### PR TITLE
Cleaning up and Updating Documentation

### PR DESCRIPTION
**Pull request by kenshaw**
Made some fairly drastic changes to README.md in order to fix some spelling and to hopefully make the documentation a bit easier to understand. I also went through and standardized the spelling of 'marshal' and 'unmarshal' throughout the code and associated documentation.

Please let me know if this is acceptable, or if I need to change anything to get this accepted. Thanks!

### CODE REVIEW

**Comment by kenshaw** [comment]
Please note that I added #87 to this one as well.

**Comment by erikdubbelboer** [comment]
I would keep it as 2 separate pull requests, that's much cleaner.

**Comment by kenshaw** [comment]
I changed it back to just a single commit.

**Comment by kenshaw** [comment]
Is there any information on this issue? If there is no interest in merging this, please close it -- I promise my feelings won't be hurt (just ribbing you, lol)!

**Pull request merged**
