### PR TITLE
Fix #27

### LINKED ISSUE #27: Unrecognized package name error
Given a `foo` package containing at least two files and a `map[string][]stuct` member:  

bar.go : 

```go
package foo

//easyjson:json
type Bar struct {
	Name  string
	Bozes map[string][]Boz
}
```

and boz.go : 

```go
package foo

//easyjson:json
type Boz struct {
	Name string
}

```

Then: 

```sh
~/go/src/github.com/jeromenerf/foo % easyjson bar.go boz.go
# github.com/jeromenerf/foo
./bar_easyjson.go:36: undefined: foo in foo.Boz
./bar_easyjson.go:43: undefined: foo in foo.Boz
Bootstrap failed: exit status 2
```

(Running `easyjson bar.go boz.go` doesn't produce any error however).

The files produced : 

```go
// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package foo

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var _ = json.RawMessage{} // suppress unused package warning

func easyjson_4347b5c1_decode_github_com_jeromenerf_foo_Bar(in *jlexer.Lexer, out *Bar) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Bozes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Bozes = make(map[string][]foo.Boz)
				} else {
					out.Bozes = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 []foo.Boz
					in.Delim('[')
					if !in.IsDelim(']') {
						v1 = make([]Boz, 0, 4)
					} else {
						v1 = nil
					}
					for !in.IsDelim(']') {
						var v2 Boz
						(v2).UnmarshalEasyJSON(in)
						v1 = append(v1, v2)
						in.WantComma()
					}
					in.Delim(']')
					(out.Bozes)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson_4347b5c1_encode_github_com_jeromenerf_foo_Bar(out *jwriter.Writer, in Bar) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Bozes\":")
	if in.Bozes == nil {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v3_first := true
		for v3_name, v3_value := range in.Bozes {
			if !v3_first {
				out.RawByte(',')
			}
			v3_first = false
			out.String(string(v3_name))
			out.RawByte(':')
			out.RawByte('[')
			for v4, v5 := range v3_value {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
		out.RawByte('}')
	}
	out.RawByte('}')
}
func (v Bar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson_4347b5c1_encode_github_com_jeromenerf_foo_Bar(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}
func (v Bar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_4347b5c1_encode_github_com_jeromenerf_foo_Bar(w, v)
}
func (v *Bar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson_4347b5c1_decode_github_com_jeromenerf_foo_Bar(&r, v)
	return r.Error()
}
func (v *Bar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson_4347b5c1_decode_github_com_jeromenerf_foo_Bar(l, v)
}
``` 

and 

```go
// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  foo

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func (* Boz ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Boz ) UnmarshalJSON([]byte) error { return nil }
func (* Boz ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Boz ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Boz *Boz
```

### PR DESCRIPTION
**Pull request by hectorj**
Fix #27, and add corresponding test case.

### CODE REVIEW

**Comment by Barberrrry** [comment]
@hectorj, tests are failed sometimes after you added `deepNestValue` case to test.
```        basic_test.go:46: [12, *tests.DeepNest] MarshalJSON(): got 
                {"SliceMap":{"testSliceMap2":[],"testSliceMap1":["0","1"]},"MapSlice":[{"testMapSlice1":"someValue"}]}
                                 want 
                {"SliceMap":{"testSliceMap1":["0","1"],"testSliceMap2":[]},"MapSlice":[{"testMapSlice1":"someValue"}]}
```
You cannot rely on items order in map. So you need to create own test function for asserting `deepNestValue` result.

**Comment by hectorj** [comment]
@Barberrrry I see. Damn, I got "lucky" to have them pass both on my local and on Travis. Will fix.

**Comment by vstarodub** [comment]
In fact, it's just a lot easier not to use a map with two items in this test. It's testing how the pieces fit together, not the serialization logic for the map itself.

**Comment by vstarodub** [comment]
Should be ok now.

**Comment by hectorj** [comment]
@vstarodub Thanks. Had nearly the same fix, but I'm a bit late it seems: https://github.com/hectorj/easyjson/commit/97dd9e332dfddfd0b79e87080bb59a174e80458c

**Pull request merged**
