### PR TITLE
Cope with nil pointer on marshal

### LINKED ISSUE #242: Marshal needs a nil check
If you try to marshal a nil value you hit a panic. easyjson should check for nil (with something like reflect.ValueOf(v).IsNil() as the interface it sees will != nil)

https://play.golang.org/p/Aokc7vTmDM3
```go
package main

import (
	"fmt"

	"github.com/mailru/easyjson"
	"github.com/mailru/easyjson/jwriter"
)

type silly struct {
}

func (s silly) MarshalEasyJSON(w *jwriter.Writer) {
	w.String("Hello")
}

func main() {
	var s *silly
	data, err := easyjson.Marshal(s)
	fmt.Println(data, err)
}
```

### PR DESCRIPTION
**Pull request by philpearl**
Should marshal to `null` not panic. Fixes #242

### CODE REVIEW

**Comment by rvasily** [comment]
This is extremely expensive check.
Main purpose of easyjson is not use of reflect package during runtime

**Comment by philpearl** [comment]
I'm away from keyboard, but it really isn't expensive. It breaks down to
following a couple of pointers and checking a flag. If you really don't
like the reflect package we can do something similar with unsafe...

**Comment by philpearl** [comment]
Quick benchmark on the nil check
```
name        time/op
NilCheck-8  6.25ns ± 4%
```

**Comment by philpearl** [comment]
@rvasily Are you opposed to this check given it takes ~6ns? If so would you accept a similar check based on the unsafe package instead?

**Pull request merged**
